
releases:
  - name: nginx-ingress
    namespace: base
    chart: ./charts/nginx-ingress
    values:
      - ./env/dev/values-nginx-ingress.yaml
    atomic: true

  - name: argocd
    namespace: argocd
    chart: ./charts/argo-cd
    version: 4.23.0
    atomic: true
    values:
      - env/dev/values-argocd.yaml

  - name: argocd-apps
    namespace: argocd
    chart: ./charts/argocd-apps
    values:
      - ./env/dev/values-argocd-apps.yaml
    needs:
      - argocd
    atomic: true

  - name: argo-rollouts
    namespace: argocd
    chart: ./charts/argo-rollouts
    values:
      - ./env/dev/values-argo-rollouts.yaml
    needs:
      - argocd
    atomic: true

helmDefaults:
  timeout: 600
