
releases:

  - name: linkerd-crds
    namespace: linkerd
    chart: ./charts/linkerd-crds
    atomic: true
    values:
      - ./env/dev/values-linkerd-crds.yaml

  - name: linkerd-control-plane
    namespace: linkerd
    chart: ./charts/linkerd-control-plane
    atomic: true
    values:
      - ./env/dev/values-linkerd-control-plane.yaml
      - ./env/dev/values-linkerd-control-plane_cert.yaml
    needs: 
      - linkerd-crds

  - name: nginx-ingress
    namespace: base
    chart: ./charts/nginx-ingress
    atomic: true
    values:
      - ./env/dev/values-nginx-ingress.yaml

  - name: argocd
    namespace: argocd
    chart: ./charts/argo-cd
    version: 4.23.0
    atomic: true
    values:
      - env/dev/values-argocd.yaml
    needs: 
      - linkerd-control-plane

  - name: argocd-apps
    namespace: argocd
    chart: ./charts/argocd-apps
    atomic: true
    values:
      - ./env/dev/values-argocd-apps.yaml
    needs:
      - argocd

  - name: argo-rollouts
    namespace: argocd
    chart: ./charts/argo-rollouts
    atomic: true
    values:
      - ./env/dev/values-argo-rollouts.yaml
    needs:
      - argocd

helmDefaults:
  timeout: 60
