controller:
  ingressClass:
    name: nginx-ingress-01

  config: 
   name: nginx-ingress-01-config

  image:
    repository: 706357943586.dkr.ecr.ap-northeast-1.amazonaws.com/tada_nginx-ingress
    tag: "3.4.0"
    pullPolicy: IfNotPresent

  ## It is recommended to use your own TLS certificates and keys
  #defaultTLS:
    #cert: ""
    #key: ""
    #secret: base/nginx-ingress-secret-01

  healthStatusURI: "/nginx-health"

  service:
    create: true
    type: NodePort
    httpPort:
      enable: true
      port: 80
      nodePort: 30080
      targetPort: 80

    httpsPort:
      enable: true
      port: 443
      nodePort: 30443
      targetPort: 443

